server {
  listen 8000;

  location = /health {
    access_log off;
    add_header content-type text/plain;
    return 200 "ok\n";
  }

  location = /rest/v1 {
    proxy_pass http://rest:3000/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header X-Client-Info $http_x_client_info;
    proxy_set_header apikey $http_apikey;
  }

  location /rest/v1/ {
    proxy_pass http://rest:3000/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header X-Client-Info $http_x_client_info;
    proxy_set_header apikey $http_apikey;
  }

  location /auth/v1/ {
    default_type application/json;
    return 501 '{"message":"Local auth is not enabled in this minimal Supabase stack."}';
  }
}
